export const types = {
  POST_REQUEST: "POST_REQUEST",
  POST_SUCCESS: "POST_SUCCESS",
  POST_FAIL: "POST_FAIL",

  COMMENT_LIST_REQUEST: "COMMENT_LIST_REQUEST",
  COMMENT_LIST_SUCCESS: "COMMENT_LIST_SUCCESS",
  COMMENT_LIST_FAIL: "COMMENT_LIST_FAIL",

  ADD_COMMENT_REQUEST: "ADD_COMMENT_REQUEST",
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  ADD_COMMENT_FAIL: "ADD_COMMENT_FAIL",

  POST_LIST_REQUEST: "POST_LIST_REQUEST",
  POST_LIST_SUCCESS: "POST_LIST_SUCCESS",
  POST_LIST_FAIL: "POST_LIST_FAIL",

  POPULAR_POSTS_REQUEST: "POPULAR_POSTS_REQUEST",
  POPULAR_POSTS_SUCCESS: "POPULAR_POSTS_SUCCESS",
  POPULAR_POSTS_FAIL: "POPULAR_POSTS_FAIL",

  POST_CAT_COUNT_REQUEST: "POST_CAT_COUNT_REQUEST",
  POST_CAT_COUNT_SUCCESS: "POST_CAT_COUNT_SUCCESS",
  POST_CAT_COUNT_FAIL: "POST_CAT_COUNT_FAIL",

  POST_CAT_REQUEST: "POST_CAT_REQUEST",
  POST_CAT_SUCCESS: "POST_CAT_SUCCESS",
  POST_CAT_FAIL: "POST_CAT_FAIL",
};
